services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network
  php:
    image: php:8.3.4-fpm
    volumes:
      - .:/var/www
    networks:
      - app-network
  tailwind-builder:
    image: node:lts-alpine
    container_name: tailwind_builder_RP
    user: "${UID}:${GID}" # adicionado
    working_dir: /app
    volumes:
      - ./:/app
    command: tail -f /dev/null # anterior: sh -c "npm install && npm run watch

networks:
  app-network:
    driver: bridge
