
    <main class="relative">
        <div class="absolute inset-0 h-[20vh] flex items-center bg-custom-gradient2 z-10">
        </div>

        <div class="absolute w-full top-[2vh] z-20 px-8">
            <div class="max-w-[400px] mx-auto p-6 py-12 bg-white shadow-md rounded-md">
                <h5 class="my-2 text-xl font-semibold text-black text-center">Entrar</h5>
                <form id="loginForm">
                    <div class="mb-4 mt-3">
                        <label for="email" class="text-black">E-mail</label>
                        <input id="email" type="email"
                            class="w-full mt-3 py-2 px-3 h-10 bg-transparent rounded outline-none border border-gray-200 focus:border-blue-400  focus:ring-0"
                            placeholder="Seu E-mail">
                    </div>

                    <div class="mb-4">
                        <label for="username" class="text-black">Senha</label>
                        <input id="username" type="password"
                            class="w-full mt-3 py-2 px-3 h-10 bg-transparent rounded outline-none border border-gray-200 focus:border-blue-400  focus:ring-0"
                            placeholder="Senha">
                    </div>

                    <div class="flex items-center mb-4">
                        <label for="" class="ml-3 text-sm font-medium text-gray-900"><a href="#"
                                class="text-blue-500">Esqueceu sua Senha?</a></label>
                    </div>

                    <div class="text-center">
                        <button
                            class="h-[50px] px-6 mt-3 bg-blue-400  text-white text-sm font-semibold rounded-full shadow-md hover:bg-blue-400 ">
                            Confirmar
                        </button>
                    </div>
                </form>
            </div>
        </div>