
<div class="grid grid-cols-3 gap-5 m-10">
    <div class="bg-white p-5 rounded-md shadow-lg w-96">
        <img src="https://picsum.photos/id/237/536/354" class="rounded-md">
        <h3 class="font-bold text-xl pb-2 pt-2">Tunico, 8</h3>
        <p>Ultima vez visto no Lago da Ordem</p>
    </div>

    <div class="bg-white p-4 rounded-md shadow-lg w-96">
        <img src="https://media.istockphoto.com/id/1483117390/photo/funny-little-pomeranian-dog-spitz-walking-outdoors.jpg?s=612x612&w=0&k=20&c=TfwD4xAvJcbVpXhPo4YQTuuVqcQfXENcuEnjfhRe4O4=" class="rounded-md">
        <h3 class="font-bold text-xl pb-2 pt-2">Lulu, 6</h3>
        <p>Ultima vez visto no Lago da Ordem</p>
    </div>

    <div class="bg-white p-4 rounded-md shadow-lg w-96">
        <img src=" https://www.hepper.com/wp-content/uploads/2022/10/Long-haired-cream-dachshund-running.jpg" class="rounded-md">
        <h3 class="font-bold text-xl pb-2 pt-2">Tobi, 4</h3>
        <p>Ultima vez visto no Lago da Ordem</p>
    </div>
</div>

<a href="/logout" class="block text-center text-sm text-blue-600 underline">Sair</a>