<main class="flex justify-center items-center  bg-gray-100 p-4">
  <div class="w-full max-w-xl bg-white shadow-lg rounded-2xl p-8">
    <h2 class="text-2xl font-semibold mb-2 text-gray-800"><?= $title ?>  </h2>

    <p class="text-gray-600 mb-6">Preencha o formulário abaixo para editar.</p>
    
    <!-- Mensagens erro ou sucesso -->
    <?php if (isset($_SESSION['flash_danger'])): ?>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
        <span class="block sm:inline"><?= htmlspecialchars($_SESSION['flash_danger']) ?></span>
      </div>
      <?php unset($_SESSION['flash_danger']); ?>
    <?php endif; ?>

    <form action="<?= route('posts.update',  ['id' => $post->id]) ?>" method="POST" 
      class="<?= $post->hasErrors() ? 'was-validated' : '' ?>" 
      novalidate enctype="multipart/form-data" >

    <input type="hidden" name="_method" value="PUT">
      
      <!-- Título -->
      <div class="mb-4">
        <label for="title" class="block text-gray-700 font-medium mb-1">Título</label>
        <input 
          type="text" 
          id="title"    
          name="post[title]"
          class="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:outline-none
                    <?= $post->errors('title') 
                      ? 'border-red-500 focus:ring-red-500 bg-red-50' 
                      : 'border-gray-300 focus:ring-blue-500' ?>"" 
          value="<?= $post->title ?>"          
          required
        >
      </div>
      <?php if ($post->errors('title')): ?>
          <p class="mt-2 text-sm text-red-600">
              <?= $post->errors('title') ?>
          </p>
      <?php endif; ?>

      <!-- description -->
      <div class="mb-4">
        <label for="description" class="block text-gray-700 font-medium mb-1">Descrição</label>
        <textarea 
          id="description"
          name="post[description]" 
          rows="4"
          class="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:outline-none
            <?= $post->errors('description') 
                      ? 'border-red-500 focus:ring-red-500 bg-red-50' 
                      : 'border-gray-300 focus:ring-blue-500' ?>"      
          required
        ><?= $post->description ?></textarea>
      </div>
      <?php if ($post->errors('description')): ?>
          <p class="mt-2 text-sm text-red-600">
              <?= $post->errors('description') ?>
          </p>
      <?php endif; ?>

      <!-- Upload de imagens -->
      <label for="path" class="block text-gray-700 font-medium mb-1">Upload da Imagem</label>
      <div class="flex items-center justify-center w-full">
          <label for="dropzone-file" class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer
           bg-gray-50  hover:bg-gray-300 
            <?= $post->errors('photos') 
                      ? 'border-red-500 focus:ring-red-500 bg-red-50' 
                      : 'border-gray-300 focus:ring-blue-500' ?>">
              <div class="flex flex-col items-center justify-center pt-5 pb-6">
                  <svg class="w-8 h-8 mb-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/>
                  </svg>
                  <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Click to upload</span> or drag and drop</p>
                  <p class="text-xs text-gray-500 dark:text-gray-400">PNG, JPG or JPGE (MAX. 800x400px)</p>
              </div>
              <input id="photos" type="file"  name="photos[]"  multiple required />
          </label>
      </div>
      <?php if ($post->errors('photos')): ?>
          <p class="mt-2 text-sm text-red-600">
              <?= $post->errors('photos') ?>
          </p>
      <?php endif; ?>

      <!-- Botões -->
      <div class="flex items-center space-x-3 pt-2">
        <button 
          type="submit" 
          class="bg-blue-600 text-white px-5 py-2 rounded-lg hover:bg-blue-700 transition" 
        >Editar Anúncio</button>    
        <a 
          href="<?= route('home.index') ?>" 
          class="bg-gray-300 text-gray-800 px-5 py-2 rounded-lg hover:bg-gray-400 transition"
        >Cancelar</a>
      </div>

    </form>
  </div>

</main>