<main class="flex justify-center items-center  bg-gray-100 p-4">
  <div class="w-full max-w-xl bg-white shadow-lg rounded-2xl p-8">
    <h2 class="text-2xl font-semibold mb-2 text-gray-800"><?= $title ?>  </h2>

    <p class="text-gray-600 mb-6">Preencha o formulário abaixo para editar.</p>
    
    <!-- Mensagens erro ou sucesso -->
    <?php if (isset($_SESSION['flash_danger'])): ?>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
        <span class="block sm:inline"><?= htmlspecialchars($_SESSION['flash_danger']) ?></span>
      </div>
      <?php unset($_SESSION['flash_danger']); ?>
    <?php endif; ?>

    <form action="<?= route('posts.update',  ['id' => $post->id]) ?>" method="POST" 
      class="<?= $post->hasErrors() ? 'was-validated' : '' ?>" 
      novalidate>

    <input type="hidden" name="_method" value="PUT">
      
      <!-- Título -->
      <div class="mb-4">
        <label for="title" class="block text-gray-700 font-medium mb-1">Título</label>
        <input 
          type="text" 
          id="title"    
          name="post[title]"
          class="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none" 
          value="<?= $post->title ?>"          
          required
        >
      </div>

      <div class="text-xl text-red-600 mt-1">
        <?= $post->errors('title') ? $post->errors('title') : '' ?>
      </div>

      <div class="mb-4">
        <label for="description" class="block text-gray-700 font-medium mb-1">Descrição</label>
        <textarea 
          id="description"
          name="post[description]" 
          rows="4"
          class="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none"      
          required
        ><?= $post->description ?></textarea>
      </div>

      <!-- Imagem URL -->
      <div class="mb-4">
        <label for="url_photo" class="block text-gray-700 font-medium mb-1">URL da Imagem</label>
        <input 
          type="text" 
          id="url_photo"
          name="post[url_photo]" 
          class="w-full border rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none" 
          value="<?= $post->url_photo ?>"
          required
        >
      </div>

      <!-- Botões -->
      <div class="flex items-center space-x-3 pt-2">
        <button 
          type="submit" 
          class="bg-blue-600 text-white px-5 py-2 rounded-lg hover:bg-blue-700 transition" 
        >Editar Anúncio</button>    
        <a 
          href="<?= route('home.index') ?>" 
          class="bg-gray-300 text-gray-800 px-5 py-2 rounded-lg hover:bg-gray-400 transition"
        >Cancelar</a>
      </div>

    </form>
  </div>

</main>