<main class="container mx-auto p-4 md:p-8 flex flex-col lg:flex-row justify-center gap-8">

    <div class="relative group max-w-xl w-full bg-white shadow-lg rounded-2xl overflow-hidden">
        <div>
            <img class="h-auto w-full max-w-full" 
                 src="<?= htmlspecialchars($post->url_photo) ?>" 
                 alt="<?= htmlspecialchars($post->title) ?>">
            <!-- delete da imagem -->
            <div class="absolute top-2 right-2 bg-black bg-opacity-40 p-1 rounded-md opacity-0 group-hover:opacity-100 transition-opacity duration-300 z-10">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="red" cursor="pointer" class="size-7">
                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                </svg>
            </div>
        </div>

        <div class="p-6 md:p-8">
            
            <h1 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
                <?= htmlspecialchars($post->title) ?>
            </h1>

            <div class="prose max-w-none text-gray-700 mb-4">
                <p><?= nl2br(htmlspecialchars($post->description)) ?></p>
            </div>

            <?php if ($username): ?>
                <div class="flex items-center text-gray-600 mb-4">
                    <span class="mr-4 px-3 py-1 bg-gray-100 text-gray-800 rounded-full font-mono text-xs">
                        <span class="font-bold">Publicado por:</span> <?= $username  ?>
                    </span>
                </div>
            <?php endif; ?>

            <div class="mt-2 pt-6 border-t">
                <a href="<?= route('home.index') ?>" 
                   class="bg-gray-300 text-gray-800 px-5 py-2 rounded-lg hover:bg-gray-400 transition">
                    &larr; Voltar
                </a>
            </div>
        </div>
    </div>

    <nav class="w-full lg:w-20 sticky top-8 h-fit">
        <ul class="flex flex-row lg:flex-col justify-around lg:gap-4 p-4 lg:p-0 bg-white lg:bg-transparent shadow-lg lg:shadow-none rounded-lg">
            <!-- adição de imagens -->
            <li>
                <a href="" 
                   class="flex flex-col items-center p-3 bg-white shadow-md rounded-lg text-gray-700 hover:bg-green-500 hover:text-white transition-all duration-300 group">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                    <span class="text-xs mt-1 font-medium">Adicionar</span>
                </a>
            </li>
            
            <!-- update de imagens -->
            <li>
                <a href="" 
                   class="flex flex-col items-center p-3 bg-white shadow-md rounded-lg text-gray-700 hover:bg-blue-500 hover:text-white transition-all duration-300 group">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 7.5h-.75A2.25 2.25 0 0 0 4.5 9.75v7.5a2.25 2.25 0 0 0 2.25 2.25h7.5a2.25 2.25 0 0 0 2.25-2.25v-7.5a2.25 2.25 0 0 0-2.25-2.25h-.75m0-3-3-3m0 0-3 3m3-3v11.25m6-2.25h.75a2.25 2.25 0 0 1 2.25 2.25v7.5a2.25 2.25 0 0 1-2.25 2.25h-7.5a2.25 2.25 0 0 1-2.25-2.25v-.75" />
                    </svg>
                   <span class="text-xs mt-1 font-medium">Atualizar</span>
                </a>
            </li>

            <!-- view da imagem -->
            <li>
                <a href="<?= htmlspecialchars($post->url_photo) ?>" 
                   target="_blank" 
                   rel="noopener noreferrer"
                   class="flex flex-col items-center p-3 bg-white shadow-md rounded-lg text-gray-700 hover:bg-gray-800 hover:text-white transition-all duration-300 group">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" />
                    </svg>                    
                    <span class="text-xs mt-1 font-medium">Expandir</span>
                </a>

            </li>

        </ul>
    </nav>
</main>