<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RadarPet</title>
    <link rel="stylesheet" href="/assets/css/application.css">
    <script src="https://cdn.tailwindcss.com"></script>

</head>

<body class="bg-gray-100 text-black">
<a href="<?= route('home.index') ?>"><h1 class="text-3xl font-bold text-blue-600 p-10">
    RadarPet
</h1></a>

    <main class="container-fluid">


        <?php require '_flash_message.phtml'; ?>

        <?php require $view ?>

    </main>
</body>

</html>